(() => {
  "use strict";
  const chapters = window.C_STUDY_CHAPTERS || [];
  const $ = (id) => document.getElementById(id);
  const el = {
    menuBtn:$("menuBtn"), closeMenuBtn:$("closeMenuBtn"), sidebar:$("sidebar"), chapterNav:$("chapterNav"), chapterLabel:$("chapterLabel"), runtimeStatus:$("runtimeStatus"), progressBtn:$("progressBtn"), progressDialog:$("progressDialog"), progressSummary:$("progressSummary"), progressList:$("progressList"), resetAllProgressBtn:$("resetAllProgressBtn"), welcome:$("welcome"), studyView:$("studyView"), startBtn:$("startBtn"), resumeBtn:$("resumeBtn"), chapterEyebrow:$("chapterEyebrow"), chapterTitle:$("chapterTitle"), chapterSummary:$("chapterSummary"), chapterPages:$("chapterPages"), markChapterBtn:$("markChapterBtn"), keyPoints:$("keyPoints"), exampleTitle:$("exampleTitle"), exampleReference:$("exampleReference"), exampleReferenceBox:$("exampleReferenceBox"), typingExampleBtn:$("typingExampleBtn"), exampleEditor:$("exampleEditor"), exampleOutput:$("exampleOutput"), runExampleBtn:$("runExampleBtn"), resetExampleBtn:$("resetExampleBtn"), exerciseTabs:$("exerciseTabs"), exerciseProgress:$("exerciseProgress"), exerciseNumber:$("exerciseNumber"), exerciseTitle:$("exerciseTitle"), exercisePrompt:$("exercisePrompt"), exerciseHint:$("exerciseHint"), exerciseSolved:$("exerciseSolved"), exerciseEditor:$("exerciseEditor"), gradeResult:$("gradeResult"), runExerciseBtn:$("runExerciseBtn"), gradeBtn:$("gradeBtn"), resetExerciseBtn:$("resetExerciseBtn"), prevChapterBtn:$("prevChapterBtn"), nextChapterBtn:$("nextChapterBtn"), toast:$("toast")
  };
  const STORAGE={solved:"c-practice-solved-v1",completed:"c-practice-completed-v1",drafts:"c-practice-drafts-v1",exampleDrafts:"c-practice-example-drafts-v1",lastChapter:"c-practice-last-chapter-v1"};
  const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
  const writeJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  let solved=readJSON(STORAGE.solved,{}),completed=readJSON(STORAGE.completed,{}),drafts=readJSON(STORAGE.drafts,{}),exampleDrafts=readJSON(STORAGE.exampleDrafts,{}),currentChapterIndex=-1,currentExerciseIndex=0,worker=null,pending=new Map(),toastTimer=null;
  function toast(message){el.toast.textContent=message;el.toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.toast.classList.remove("show"),1800)}
  function setRuntimeStatus(text,state=""){el.runtimeStatus.textContent=text;el.runtimeStatus.className="status-pill"+(state?" "+state:"")}
  function createWorker(){if(worker)worker.terminate();worker=new Worker("./runner-worker.js");worker.onmessage=(event)=>{const msg=event.data||{},job=pending.get(msg.id);if(!job)return;pending.delete(msg.id);clearTimeout(job.timer);msg.ok?job.resolve(msg.output??""):job.reject(new Error(msg.error||"C 실행 오류"))};worker.onerror=(event)=>{for(const[,job]of pending){clearTimeout(job.timer);job.reject(new Error(event.message||"C 실행기 오류"))}pending.clear();setRuntimeStatus("C 실행기 오류","error")}}
  function runC(code,timeoutMs=6500){if(!worker)createWorker();return new Promise((resolve,reject)=>{const id=crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();const timer=setTimeout(()=>{pending.delete(id);if(worker)worker.terminate();worker=null;reject(new Error("실행 시간이 초과되었습니다. 무한 반복이 있는지 확인하세요."))},timeoutMs);pending.set(id,{resolve,reject,timer});worker.postMessage({id,code})})}
  function normalizeLines(output){return String(output).replace(/\r\n/g,"\n").replace(/\r/g,"\n").split("\n").map(s=>s.trim()).filter((s,i,arr)=>s.length>0||(i<arr.length-1&&arr[i+1].length>0))}
  async function warmRuntime(){setRuntimeStatus("C 실행기 준비 중");try{const out=await runC('#include <stdio.h>\nint main(void){printf("READY\\n");return 0;}\n',9000);setRuntimeStatus(String(out).includes("READY")?"C 실행기 준비됨":"C 실행기 연결됨","ready")}catch(e){setRuntimeStatus("C 실행기 로드 실패","error");console.warn(e)}}
  function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function renderNav(){el.chapterNav.innerHTML="";chapters.forEach((ch,i)=>{const b=document.createElement("button");b.type="button";b.className="chapter-link"+(i===currentChapterIndex?" active":"");b.innerHTML=`<span class="chapter-num">${String(ch.id).padStart(2,"0")}</span><span class="chapter-name">${escapeHTML(ch.title)}</span><span class="chapter-check">${completed[ch.id]?"✓":""}</span>`;b.addEventListener("click",()=>{openChapter(i);closeMenu()});el.chapterNav.appendChild(b)})}
  function openMenu(){el.sidebar.classList.add("open")} function closeMenu(){el.sidebar.classList.remove("open")}
  function openChapter(index,exerciseIndex=0){index=Math.max(0,Math.min(chapters.length-1,index));currentChapterIndex=index;currentExerciseIndex=Math.max(0,exerciseIndex);const ch=chapters[index];localStorage.setItem(STORAGE.lastChapter,String(ch.id));el.welcome.hidden=true;el.studyView.hidden=false;el.chapterLabel.textContent=`CH ${String(ch.id).padStart(2,"0")} · ${ch.title}`;el.chapterEyebrow.textContent=`CHAPTER ${String(ch.id).padStart(2,"0")}`;el.chapterTitle.textContent=ch.title;el.chapterSummary.textContent=ch.summary;el.chapterPages.textContent=`교재 ${ch.pages}쪽`;el.markChapterBtn.textContent=completed[ch.id]?"✓ 학습 완료":"학습 완료 표시";el.keyPoints.innerHTML="";ch.points.forEach(point=>{const li=document.createElement("li");li.textContent=point;el.keyPoints.appendChild(li)});el.exampleTitle.textContent=ch.example.title;el.exampleReference.textContent=ch.example.code;el.exampleReferenceBox.open=false;el.exampleEditor.value=exampleDrafts[ch.id]??ch.example.code;el.exampleOutput.textContent="$ 실행 버튼을 누르세요.";renderExerciseTabs();openExercise(Math.min(currentExerciseIndex,ch.exercises.length-1));updateChapterButtons();renderNav();window.scrollTo({top:0,behavior:"smooth"})}
  function renderExerciseTabs(){const ch=chapters[currentChapterIndex];el.exerciseTabs.innerHTML="";ch.exercises.forEach((ex,i)=>{const b=document.createElement("button");b.type="button";b.role="tab";b.className="exercise-tab"+(i===currentExerciseIndex?" active":"");b.textContent=`${i+1}. ${ex.title}${solved[ex.id]?" ✓":""}`;b.addEventListener("click",()=>openExercise(i));el.exerciseTabs.appendChild(b)});const done=ch.exercises.filter(ex=>solved[ex.id]).length;el.exerciseProgress.textContent=`${done} / ${ch.exercises.length} 해결`}
  function openExercise(index){const ch=chapters[currentChapterIndex];currentExerciseIndex=Math.max(0,Math.min(ch.exercises.length-1,index));const ex=ch.exercises[currentExerciseIndex];el.exerciseNumber.textContent=`문제 ${currentExerciseIndex+1}`;el.exerciseTitle.textContent=ex.title;el.exercisePrompt.textContent=ex.prompt;el.exerciseHint.textContent=ex.hint;el.exerciseEditor.value=drafts[ex.id]??ex.starter;el.gradeResult.className="grade-result";el.gradeResult.textContent="코드를 작성한 뒤 채점해 보세요.";updateSolveState();renderExerciseTabs()}
  function updateSolveState(){const ex=chapters[currentChapterIndex].exercises[currentExerciseIndex];el.exerciseSolved.textContent=solved[ex.id]?"✓ 해결함":"미해결";el.exerciseSolved.className="solve-state"+(solved[ex.id]?" solved":"")}
  function updateChapterButtons(){const ch=chapters[currentChapterIndex];el.prevChapterBtn.disabled=currentChapterIndex===0;el.nextChapterBtn.disabled=currentChapterIndex===chapters.length-1;el.nextChapterBtn.textContent=currentChapterIndex===chapters.length-1?"마지막 장":"다음 장 →";el.markChapterBtn.textContent=completed[ch.id]?"✓ 학습 완료":"학습 완료 표시"}
  async function runExample(){const ch=chapters[currentChapterIndex];exampleDrafts[ch.id]=el.exampleEditor.value;writeJSON(STORAGE.exampleDrafts,exampleDrafts);el.runExampleBtn.disabled=true;el.exampleOutput.textContent="$ 컴파일 및 실행 중...";try{const out=await runC(el.exampleEditor.value);el.exampleOutput.textContent=out||"(출력 없음)";setRuntimeStatus("C 실행기 준비됨","ready")}catch(e){el.exampleOutput.textContent="실행 실패\n"+e.message;setRuntimeStatus("실행 오류 확인","error")}finally{el.runExampleBtn.disabled=false}}
  function buildExerciseProgram(ex){const userCode=el.exerciseEditor.value;if(/\b(?:int|void|char|long|double|float)?\s*main\s*\(/.test(userCode))throw new Error("연습문제에서는 main 함수를 작성하지 마세요. 제시된 함수/매크로만 완성하면 테스트 코드가 자동으로 붙습니다.");return `${userCode}\n\n/* --- C Practice Page test harness --- */\n${ex.harness}\n`}
  async function executeExercise(doGrade){const ex=chapters[currentChapterIndex].exercises[currentExerciseIndex];drafts[ex.id]=el.exerciseEditor.value;writeJSON(STORAGE.drafts,drafts);el.gradeBtn.disabled=true;el.runExerciseBtn.disabled=true;el.gradeResult.className="grade-result running";el.gradeResult.textContent=doGrade?"컴파일 → 테스트 실행 → 결과 비교 중...":"컴파일 및 실행 중...";try{const out=await runC(buildExerciseProgram(ex)),actual=normalizeLines(out);if(!doGrade){el.gradeResult.className="grade-result";el.gradeResult.textContent=`실행 결과\n${out||"(출력 없음)"}\n\n※ 실행만 했습니다. 정답 판정은 '채점하기'를 누르세요.`;return}const expected=ex.expected.map(v=>String(v).trim()),max=Math.max(expected.length,actual.length);let passCount=0;const lines=[];for(let i=0;i<max;i++){const ok=expected[i]!==undefined&&actual[i]!==undefined&&expected[i]===actual[i];if(ok)passCount++;lines.push(`${ok?"✅":"❌"} Test ${i+1}`+(ok?`  → ${actual[i]}`:`\n   예상: ${expected[i]??"(없음)"}\n   출력: ${actual[i]??"(출력 없음)"}`))}const allPass=passCount===expected.length&&actual.length===expected.length;if(allPass){solved[ex.id]=true;writeJSON(STORAGE.solved,solved);el.gradeResult.className="grade-result pass";el.gradeResult.textContent=`정답입니다! ${expected.length}/${expected.length} 테스트 통과\n\n${lines.join("\n")}`;toast("연습문제 해결 ✓");updateSolveState();renderExerciseTabs()}else{el.gradeResult.className="grade-result fail";const looksLikeCompilerError=/error|failed|undefined|parse|line\s+\d+/i.test(String(out));el.gradeResult.textContent=`${looksLikeCompilerError?"컴파일/실행 오류 또는 오답":"아직 정답이 아닙니다."} ${passCount}/${expected.length} 테스트 통과\n\n${lines.join("\n")}`+(looksLikeCompilerError?`\n\n원본 실행 출력:\n${out}`:"")}setRuntimeStatus("C 실행기 준비됨","ready")}catch(e){el.gradeResult.className="grade-result fail";el.gradeResult.textContent="실행 실패\n"+e.message;setRuntimeStatus("실행 오류 확인","error")}finally{el.gradeBtn.disabled=false;el.runExerciseBtn.disabled=false}}
  function renderProgress(){const totalExercises=chapters.reduce((n,ch)=>n+ch.exercises.length,0),solvedCount=chapters.reduce((n,ch)=>n+ch.exercises.filter(ex=>solved[ex.id]).length,0),completedCount=chapters.filter(ch=>completed[ch.id]).length;el.progressSummary.innerHTML=`<p><strong>${completedCount}/${chapters.length}</strong>개 장 학습 완료 · <strong>${solvedCount}/${totalExercises}</strong>개 연습문제 해결</p>`;el.progressList.innerHTML="";chapters.forEach(ch=>{const done=ch.exercises.filter(ex=>solved[ex.id]).length,row=document.createElement("div");row.className="progress-row";row.innerHTML=`<strong>${String(ch.id).padStart(2,"0")}</strong><div>${escapeHTML(ch.title)}<br><small>${done}/${ch.exercises.length} 문제 해결</small></div><span>${completed[ch.id]?"✓":"—"}</span>`;el.progressList.appendChild(row)})}
  el.menuBtn.addEventListener("click",openMenu);el.closeMenuBtn.addEventListener("click",closeMenu);el.startBtn.addEventListener("click",()=>openChapter(0));el.resumeBtn.addEventListener("click",()=>{const lastId=Number(localStorage.getItem(STORAGE.lastChapter)||1),index=chapters.findIndex(c=>c.id===lastId);openChapter(index>=0?index:0)});
  el.typingExampleBtn.addEventListener("click",()=>{const ch=chapters[currentChapterIndex];el.exampleReferenceBox.open=true;el.exampleEditor.value="";exampleDrafts[ch.id]="";writeJSON(STORAGE.exampleDrafts,exampleDrafts);el.exampleOutput.textContent="$ 예제 원본을 보면서 직접 입력해 보세요.";el.exampleEditor.focus();toast("따라치기 모드: 편집기를 비웠습니다.")});
  el.runExampleBtn.addEventListener("click",runExample);el.resetExampleBtn.addEventListener("click",()=>{const ch=chapters[currentChapterIndex];el.exampleEditor.value=ch.example.code;delete exampleDrafts[ch.id];writeJSON(STORAGE.exampleDrafts,exampleDrafts);toast("예제 코드를 되돌렸습니다.")});el.gradeBtn.addEventListener("click",()=>executeExercise(true));el.runExerciseBtn.addEventListener("click",()=>executeExercise(false));el.resetExerciseBtn.addEventListener("click",()=>{const ex=chapters[currentChapterIndex].exercises[currentExerciseIndex];el.exerciseEditor.value=ex.starter;delete drafts[ex.id];writeJSON(STORAGE.drafts,drafts);el.gradeResult.className="grade-result";el.gradeResult.textContent="초기 코드로 되돌렸습니다."});
  el.exampleEditor.addEventListener("input",()=>{if(currentChapterIndex<0)return;exampleDrafts[chapters[currentChapterIndex].id]=el.exampleEditor.value;writeJSON(STORAGE.exampleDrafts,exampleDrafts)});el.exerciseEditor.addEventListener("input",()=>{if(currentChapterIndex<0)return;const ex=chapters[currentChapterIndex].exercises[currentExerciseIndex];drafts[ex.id]=el.exerciseEditor.value;writeJSON(STORAGE.drafts,drafts)});
  el.markChapterBtn.addEventListener("click",()=>{const ch=chapters[currentChapterIndex];completed[ch.id]=!completed[ch.id];writeJSON(STORAGE.completed,completed);updateChapterButtons();renderNav();toast(completed[ch.id]?"학습 완료로 표시했습니다.":"완료 표시를 해제했습니다.")});el.prevChapterBtn.addEventListener("click",()=>{if(currentChapterIndex>0)openChapter(currentChapterIndex-1)});el.nextChapterBtn.addEventListener("click",()=>{if(currentChapterIndex<chapters.length-1)openChapter(currentChapterIndex+1)});
  el.progressBtn.addEventListener("click",()=>{renderProgress();if(typeof el.progressDialog.showModal==="function")el.progressDialog.showModal();else el.progressDialog.setAttribute("open","")});el.resetAllProgressBtn.addEventListener("click",()=>{if(!confirm("해결 기록, 완료 표시, 작성 중인 코드까지 모두 초기화할까요?"))return;solved={};completed={};drafts={};exampleDrafts={};Object.values(STORAGE).forEach(k=>localStorage.removeItem(k));writeJSON(STORAGE.solved,solved);writeJSON(STORAGE.completed,completed);writeJSON(STORAGE.drafts,drafts);writeJSON(STORAGE.exampleDrafts,exampleDrafts);renderProgress();renderNav();if(currentChapterIndex>=0)openChapter(currentChapterIndex,currentExerciseIndex);toast("진도를 초기화했습니다.")});
  document.addEventListener("keydown",e=>{if(!(e.ctrlKey||e.metaKey)||e.key!=="Enter")return;if(document.activeElement===el.exampleEditor){e.preventDefault();runExample()}else if(document.activeElement===el.exerciseEditor){e.preventDefault();executeExercise(e.shiftKey)}});document.addEventListener("click",e=>{if(window.innerWidth<=860&&el.sidebar.classList.contains("open")&&!el.sidebar.contains(e.target)&&e.target!==el.menuBtn)closeMenu()});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(console.warn));renderNav();warmRuntime();
})();
